### ISSUE TITLE
Trying to verify contract on etherscan, bytecode slightly different

### ISSUE THREAD

**Issue by jamesjguthrie** [vittominacori/erc20-generator#1]
First of all, love the project. Used the dApp built from the source and deployed my contract.

The bytecode that got deployed is:
`0x6006805460a060020a60ff021916905560e0604052602f60808190527f68747470733a2f2f766974746f6d696e61636f72692e6769746875622e696f2f60a09081527f65726332302d67656e657261746f72000000000000000000000000000000000060c052620000749160089190620002e7565b503480156200008257600080fd5b506040516200180e3803806200180e833981016040908152815160208084015192840151918401805190949390930192849184918491620000c991600091860190620002e7565b508151620000df906001906020850190620002e7565b506002805460ff90921660ff19909216919091179055505060068054600160a060020a0319163317908190556200012890600160a060020a031664010000000062000131810204565b5050506200038c565b600654600160a060020a031633146200014957600080fd5b62000199816040805190810160405280600681526020017f6d696e74657200000000000000000000000000000000000000000000000000008152506200019c640100000000026401000000009004565b50565b62000218826007836040518082805190602001908083835b60208310620001d55780518252601f199092019160209182019101620001b4565b51815160209384036101000a6000190180199092169116179052920194855250604051938490030190922092915050640100000000620002c28102620013e11704565b81600160a060020a03167fbfec83d64eaa953f2708271a023ab9ee82057f8f3578d548c1a4ba0b5b700489826040518080602001828103825283818151815260200191508051906020019080838360005b838110156200028357818101518382015260200162000269565b50505050905090810190601f168015620002b15780820380516001836020036101000a031916815260200191505b509250505060405180910390a25050565b600160a060020a0316600090815260209190915260409020805460ff19166001179055565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106200032a57805160ff19168380011785556200035a565b828001600101855582156200035a579182015b828111156200035a5782518255916020019190600101906200033d565b50620003689291506200036c565b5090565b6200038991905b8082111562000368576000815560010162000373565b90565b611472806200039c6000396000f3006080604052600436106101485763ffffffff7c010000000000000000000000000000000000000000000000000000000060003504166305d2035b811461014d57806306fdde0314610176578063095ea7b3146102005780630988ca8c1461022457806318160ddd1461028d578063217fe6c6146102b457806323b872dd1461031b5780633092afd514610345578063313ce5671461036657806340c10f191461039157806342966c68146103b557806366188463146103cd57806370a08231146103f1578063715018a6146104125780637d64bcb4146104275780638da5cb5b1461043c57806392afc33a1461046d57806395d89b4114610482578063983b2d5614610497578063a9059cbb146104b8578063b60b7084146104dc578063d73dd623146104f1578063dc39d06d14610515578063dd62ed3e14610539578063f2fde38b14610560575b600080fd5b34801561015957600080fd5b50610162610581565b604080519115158252519081900360200190f35b34801561018257600080fd5b5061018b6105a2565b6040805160208082528351818301528351919283929083019185019080838360005b838110156101c55781810151838201526020016101ad565b50505050905090810190601f1680156101f25780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b34801561020c57600080fd5b50610162600160a060020a0360043516602435610630565b34801561023057600080fd5b5060408051602060046024803582810135601f810185900485028601850190965285855261028b958335600160a060020a03169536956044949193909101919081908401838280828437509497506106969650505050505050565b005b34801561029957600080fd5b506102a2610704565b60408051918252519081900360200190f35b3480156102c057600080fd5b5060408051602060046024803582810135601f8101859004850286018501909652858552610162958335600160a060020a031695369560449491939091019190819084018382808284375094975061070a9650505050505050565b34801561032757600080fd5b50610162600160a060020a036004358116906024351660443561077d565b34801561035157600080fd5b5061028b600160a060020a03600435166108e2565b34801561037257600080fd5b5061037b610929565b6040805160ff9092168252519081900360200190f35b34801561039d57600080fd5b50610162600160a060020a0360043516602435610932565b3480156103c157600080fd5b5061028b600435610a52565b3480156103d957600080fd5b50610162600160a060020a0360043516602435610a5c565b3480156103fd57600080fd5b506102a2600160a060020a0360043516610b4b565b34801561041e57600080fd5b5061028b610b66565b34801561043357600080fd5b50610162610bd4565b34801561044857600080fd5b50610451610c7a565b60408051600160a060020a039092168252519081900360200190f35b34801561047957600080fd5b5061018b610c89565b34801561048e57600080fd5b5061018b610cae565b3480156104a357600080fd5b5061028b600160a060020a0360043516610d08565b3480156104c457600080fd5b50610162600160a060020a0360043516602435610d4c565b3480156104e857600080fd5b5061018b610e1b565b3480156104fd57600080fd5b50610162600160a060020a0360043516602435610e76565b34801561052157600080fd5b50610162600160a060020a0360043516602435610f0f565b34801561054557600080fd5b506102a2600160a060020a0360043581169060243516610fcb565b34801561056c57600080fd5b5061028b600160a060020a0360043516610ff6565b60065474010000000000000000000000000000000000000000900460ff1681565b6000805460408051602060026001851615610100026000190190941693909304601f810184900484028201840190925281815292918301828280156106285780601f106105fd57610100808354040283529160200191610628565b820191906000526020600020905b81548152906001019060200180831161060b57829003601f168201915b505050505081565b336000818152600560209081526040808320600160a060020a038716808552908352818420869055815186815291519394909390927f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925928290030190a350600192915050565b610700826007836040518082805190602001908083835b602083106106cc5780518252601f1990920191602091820191016106ad565b51815160209384036101000a6000190180199092169116179052920194855250604051938490030190922092915050611016565b5050565b60045490565b6000610776836007846040518082805190602001908083835b602083106107425780518252601f199092019160209182019101610723565b51815160209384036101000a600019018019909216911617905292019485525060405193849003019092209291505061102b565b9392505050565b600160a060020a0383166000908152600360205260408120548211156107a257600080fd5b600160a060020a03841660009081526005602090815260408083203384529091529020548211156107d257600080fd5b600160a060020a03831615156107e757600080fd5b600160a060020a038416600090815260036020526040902054610810908363ffffffff61104a16565b600160a060020a038086166000908152600360205260408082209390935590851681522054610845908363ffffffff61105c16565b600160a060020a038085166000908152600360209081526040808320949094559187168152600582528281203382529091522054610889908363ffffffff61104a16565b600160a060020a0380861660008181526005602090815260408083203384528252918290209490945580518681529051928716939192600080516020611427833981519152929181900390910190a35060019392505050565b600654600160a060020a031633146108f957600080fd5b6109268160408051908101604052806006815260200160008051602061140783398151915281525061106f565b50565b60025460ff1681565b600061096133604080519081016040528060068152602001600080516020611407833981519152815250610696565b60065474010000000000000000000000000000000000000000900460ff161561098957600080fd5b60045461099c908363ffffffff61105c16565b600455600160a060020a0383166000908152600360205260409020546109c8908363ffffffff61105c16565b600160a060020a038416600081815260036020908152604091829020939093558051858152905191927f0f6798a560793a54c3bcfe86a93cde1e73087d944c0ea20544137d412139688592918290030190a2604080518381529051600160a060020a038516916000916000805160206114278339815191529181900360200190a350600192915050565b6109263382611180565b336000908152600560209081526040808320600160a060020a0386168452909152812054808310610ab057336000908152600560209081526040808320600160a060020a0388168452909152812055610ae5565b610ac0818463ffffffff61104a16565b336000908152600560209081526040808320600160a060020a03891684529091529020555b336000818152600560209081526040808320600160a060020a0389168085529083529281902054815190815290519293927f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925929181900390910190a35060019392505050565b600160a060020a031660009081526003602052604090205490565b600654600160a060020a03163314610b7d57600080fd5b600654604051600160a060020a03909116907ff8df31144d9c2f0f6b59d69b8b98abd5459d07f2742c4df920b25aae33c6482090600090a26006805473ffffffffffffffffffffffffffffffffffffffff19169055565b600654600090600160a060020a03163314610bee57600080fd5b60065474010000000000000000000000000000000000000000900460ff1615610c1657600080fd5b6006805474ff00000000000000000000000000000000000000001916740100000000000000000000000000000000000000001790556040517fae5184fba832cb2b1f702aca6117b8d265eaf03ad33eb133f19dde0f5920fa0890600090a150600190565b600654600160a060020a031681565b6040805180820190915260068152600080516020611407833981519152602082015281565b60018054604080516020600284861615610100026000190190941693909304601f810184900484028201840190925281815292918301828280156106285780601f106105fd57610100808354040283529160200191610628565b600654600160a060020a03163314610d1f57600080fd5b6109268160408051908101604052806006815260200160008051602061140783398151915281525061126f565b33600090815260036020526040812054821115610d6857600080fd5b600160a060020a0383161515610d7d57600080fd5b33600090815260036020526040902054610d9d908363ffffffff61104a16565b3360009081526003602052604080822092909255600160a060020a03851681522054610dcf908363ffffffff61105c16565b600160a060020a0384166000818152600360209081526040918290209390935580518581529051919233926000805160206114278339815191529281900390910190a350600192915050565b6008805460408051602060026001851615610100026000190190941693909304601f810184900484028201840190925281815292918301828280156106285780601f106105fd57610100808354040283529160200191610628565b336000908152600560209081526040808320600160a060020a0386168452909152812054610eaa908363ffffffff61105c16565b336000818152600560209081526040808320600160a060020a0389168085529083529281902085905580519485525191937f8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925929081900390910190a350600192915050565b600654600090600160a060020a03163314610f2957600080fd5b600654604080517fa9059cbb000000000000000000000000000000000000000000000000000000008152600160a060020a0392831660048201526024810185905290519185169163a9059cbb916044808201926020929091908290030181600087803b158015610f9857600080fd5b505af1158015610fac573d6000803e3d6000fd5b505050506040513d6020811015610fc257600080fd5b50519392505050565b600160a060020a03918216600090815260056020908152604080832093909416825291909152205490565b600654600160a060020a0316331461100d57600080fd5b61092681611341565b611020828261102b565b151561070057600080fd5b600160a060020a03166000908152602091909152604090205460ff1690565b60008282111561105657fe5b50900390565b8181018281101561106957fe5b92915050565b6110d9826007836040518082805190602001908083835b602083106110a55780518252601f199092019160209182019101611086565b51815160209384036101000a60001901801990921691161790529201948552506040519384900301909220929150506113bf565b81600160a060020a03167fd211483f91fc6eff862467f8de606587a30c8fc9981056f051b897a418df803a826040518080602001828103825283818151815260200191508051906020019080838360005b8381101561114257818101518382015260200161112a565b50505050905090810190601f16801561116f5780820380516001836020036101000a031916815260200191505b509250505060405180910390a25050565b600160a060020a0382166000908152600360205260409020548111156111a557600080fd5b600160a060020a0382166000908152600360205260409020546111ce908263ffffffff61104a16565b600160a060020a0383166000908152600360205260409020556004546111fa908263ffffffff61104a16565b600455604080518281529051600160a060020a038416917fcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca5919081900360200190a2604080518281529051600091600160a060020a038516916000805160206114278339815191529181900360200190a35050565b6112d9826007836040518082805190602001908083835b602083106112a55780518252601f199092019160209182019101611286565b51815160209384036101000a60001901801990921691161790529201948552506040519384900301909220929150506113e1565b81600160a060020a03167fbfec83d64eaa953f2708271a023ab9ee82057f8f3578d548c1a4ba0b5b700489826040518080602001828103825283818151815260200191508051906020019080838360008381101561114257818101518382015260200161112a565b600160a060020a038116151561135657600080fd5b600654604051600160a060020a038084169216907f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e090600090a36006805473ffffffffffffffffffffffffffffffffffffffff1916600160a060020a0392909216919091179055565b600160a060020a0316600090815260209190915260409020805460ff19169055565b600160a060020a0316600090815260209190915260409020805460ff1916600117905556006d696e7465720000000000000000000000000000000000000000000000000000ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef{bzzr}000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000b47757468726965436f696e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034743540000000000000000000000000000000000000000000000000000000000`

The bytecode that gets compiled when I try to validate using the source code you provide at https://github.com/vittominacori/erc20-generator/blob/master/dist/ERC20Token.sol is:
`0x6006805460a060020a60ff021916905560e0604052602f60808190527f68747470733a2f2f766974746f6d696e61636f72692e6769746875622e696f2f60a09081527f65726332302d67656e657261746f72000000000000000000000000000000000060c052620000749160089190620002e7565b503480156200008257600080fd5b506040516200173a3803806200173a833981016040908152815160208084015192840151918401805190949390930192849184918491620000c991600091860190620002e7565b508151620000df906001906020850190620002e7565b506002805460ff90921660ff19909216919091179055505060068054600160a060020a0319163317908190556200012890600160a060020a031664010000000062000131810204565b5050506200038c565b600654600160a060020a031633146200014957600080fd5b62000199816040805190810160405280600681526020017f6d696e74657200000000000000000000000000000000000000000000000000008152506200019c640100000000026401000000009004565b50565b62000218826007836040518082805190602001908083835b60208310620001d55780518252601f199092019160209182019101620001b4565b51815160209384036101000a6000190180199092169116179052920194855250604051938490030190922092915050640100000000620002c281026200130d1704565b81600160a060020a03167fbfec83d64eaa953f2708271a023ab9ee82057f8f3578d548c1a4ba0b5b700489826040518080602001828103825283818151815260200191508051906020019080838360005b838110156200028357818101518382015260200162000269565b50505050905090810190601f168015620002b15780820380516001836020036101000a031916815260200191505b509250505060405180910390a25050565b600160a060020a0316600090815260209190915260409020805460ff19166001179055565b828054600181600116156101000203166002900490600052602060002090601f016020900481019282601f106200032a57805160ff19168380011785556200035a565b828001600101855582156200035a579182015b828111156200035a5782518255916020019190600101906200033d565b50620003689291506200036c565b5090565b6200038991905b8082111562000368576000815560010162000373565b90565b61139e806200039c6000396000f30060806040526004361061012f5763ffffffff60e060020a60003504166305d2035b811461013457806306fdde031461015d578063095ea7b3146101e75780630988ca8c1461020b57806318160ddd14610274578063217fe6c61461029b57806323b872dd146103025780633092afd51461032c578063313ce5671461034d57806340c10f191461037857806342966c681461039c57806366188463146103b457806370a08231146103d8578063715018a6146103f95780637d64bcb41461040e5780638da5cb5b1461042357806392afc33a1461045457806395d89b4114610469578063983b2d561461047e578063a9059cbb1461049f578063b60b7084146104c3578063d73dd623146104d8578063dc39d06d146104fc578063dd62ed3e14610520578063f2fde38b14610547575b600080fd5b34801561014057600080fd5b50610149610568565b604080519115158252519081900360200190f35b34801561016957600080fd5b50610172610578565b6040805160208082528351818301528351919283929083019185019080838360005b838110156101ac578181015183820152602001610194565b50505050905090810190601f1680156101d95780820380516001836020036101000a031916815260200191505b509250505060405180910390f35b3480156101f357600080fd5b50610149600160a060020a0360043516602435610606565b34801561021757600080fd5b5060408051602060046024803582810135601f8101859004850286018501909652858552610272958335600160a060020a031695369560449491939091019190819084018382808284375094975061065a9650505050505050565b005b34801561028057600080fd5b506102896106c8565b60408051918252519081900360200190f35b3480156102a757600080fd5b5060408051602060046024803582810135601f8101859004850286018501909652858552610149958335600160a060020a03169536956044949193909101919081908401838280828437509497506106ce9650505050505050565b34801561030e57600080fd5b50610149600160a060020a0360043581169060243516604435610741565b34801561033857600080fd5b50610272600160a060020a03600435166108a8565b34801561035957600080fd5b506103626108ed565b6040805160ff9092168252519081900360200190f35b34801561038457600080fd5b50610149600160a060020a03600435166024356108f6565b3480156103a857600080fd5b50610272600435610a03565b3480156103c057600080fd5b50610149600160a060020a0360043516602435610a0d565b3480156103e457600080fd5b50610289600160a060020a0360043516610aeb565b34801561040557600080fd5b50610272610b06565b34801561041a57600080fd5b50610149610b67565b34801561042f57600080fd5b50610438610bdd565b60408051600160a060020a039092168252519081900360200190f35b34801561046057600080fd5b50610172610bec565b34801561047557600080fd5b50610172610c0f565b34801561048a57600080fd5b50610272600160a060020a0360043516610c69565b3480156104ab57600080fd5b50610149600160a060020a0360043516602435610cab565b3480156104cf57600080fd5b50610172610d7c565b3480156104e457600080fd5b50610149600160a060020a0360043516602435610dd7565b34801561050857600080fd5b50610149600160a060020a0360043516602435610e5e565b34801561052c57600080fd5b50610289600160a060020a0360043581169060243516610f04565b34801561055357600080fd5b50610272600160a060020a0360043516610f2f565b60065460a060020a900460ff1681565b6000805460408051602060026001851615610100026000190190941693909304601f810184900484028201840190925281815292918301828280156105fe5780601f106105d3576101008083540402835291602001916105fe565b820191906000526020600020905b8154815290600101906020018083116105e157829003601f168201915b505050505081565b336000818152600560209081526040808320600160a060020a03871680855290835281842086905581518681529151939490939092600080516020611353833981519152928290030190a350600192915050565b6106c4826007836040518082805190602001908083835b602083106106905780518252601f199092019160209182019101610671565b51815160209384036101000a6000190180199092169116179052920194855250604051938490030190922092915050610f4f565b5050565b60045490565b600061073a836007846040518082805190602001908083835b602083106107065780518252601f1990920191602091820191016106e7565b51815160209384036101000a6000190180199092169116179052920194855250604051938490030190922092915050610f64565b9392505050565b6000600160a060020a038316151561075857600080fd5b600160a060020a03841660009081526003602052604090205482111561077d57600080fd5b600160a060020a03841660009081526005602090815260408083203384529091529020548211156107ad57600080fd5b600160a060020a0384166000908152600360205260409020546107d6908363ffffffff610f8316565b600160a060020a03808616600090815260036020526040808220939093559085168152205461080b908363ffffffff610f9516565b600160a060020a03808516600090815260036020908152604080832094909455918716815260058252828120338252909152205461084f908363ffffffff610f8316565b600160a060020a0380861660008181526005602090815260408083203384528252918290209490945580518681529051928716939192600080516020611333833981519152929181900390910190a35060019392505050565b600654600160a060020a031633146108bf57600080fd5b6108ea8160408051908101604052806006815260200160d160020a6536b4b73a32b902815250610fa8565b50565b60025460ff1681565b60006109233360408051908101604052806006815260200160d160020a6536b4b73a32b90281525061065a565b60065460a060020a900460ff161561093a57600080fd5b60045461094d908363ffffffff610f9516565b600455600160a060020a038316600090815260036020526040902054610979908363ffffffff610f9516565b600160a060020a038416600081815260036020908152604091829020939093558051858152905191927f0f6798a560793a54c3bcfe86a93cde1e73087d944c0ea20544137d412139688592918290030190a2604080518381529051600160a060020a038516916000916000805160206113338339815191529181900360200190a350600192915050565b6108ea33826110b9565b336000908152600560209081526040808320600160a060020a038616845290915281205480831115610a6257336000908152600560209081526040808320600160a060020a0388168452909152812055610a97565b610a72818463ffffffff610f8316565b336000908152600560209081526040808320600160a060020a03891684529091529020555b336000818152600560209081526040808320600160a060020a038916808552908352928190205481519081529051929392600080516020611353833981519152929181900390910190a35060019392505050565b600160a060020a031660009081526003602052604090205490565b600654600160a060020a03163314610b1d57600080fd5b600654604051600160a060020a03909116907ff8df31144d9c2f0f6b59d69b8b98abd5459d07f2742c4df920b25aae33c6482090600090a260068054600160a060020a0319169055565b600654600090600160a060020a03163314610b8157600080fd5b60065460a060020a900460ff1615610b9857600080fd5b6006805460a060020a60ff02191660a060020a1790556040517fae5184fba832cb2b1f702aca6117b8d265eaf03ad33eb133f19dde0f5920fa0890600090a150600190565b600654600160a060020a031681565b604080518082019091526006815260d160020a6536b4b73a32b902602082015281565b60018054604080516020600284861615610100026000190190941693909304601f810184900484028201840190925281815292918301828280156105fe5780601f106105d3576101008083540402835291602001916105fe565b600654600160a060020a03163314610c8057600080fd5b6108ea8160408051908101604052806006815260200160d160020a6536b4b73a32b9028152506111a8565b6000600160a060020a0383161515610cc257600080fd5b33600090815260036020526040902054821115610cde57600080fd5b33600090815260036020526040902054610cfe908363ffffffff610f8316565b3360009081526003602052604080822092909255600160a060020a03851681522054610d30908363ffffffff610f9516565b600160a060020a0384166000818152600360209081526040918290209390935580518581529051919233926000805160206113338339815191529281900390910190a350600192915050565b6008805460408051602060026001851615610100026000190190941693909304601f810184900484028201840190925281815292918301828280156105fe5780601f106105d3576101008083540402835291602001916105fe565b336000908152600560209081526040808320600160a060020a0386168452909152812054610e0b908363ffffffff610f9516565b336000818152600560209081526040808320600160a060020a038916808552908352928190208590558051948552519193600080516020611353833981519152929081900390910190a350600192915050565b600654600090600160a060020a03163314610e7857600080fd5b6006546040805160e060020a63a9059cbb028152600160a060020a0392831660048201526024810185905290519185169163a9059cbb916044808201926020929091908290030181600087803b158015610ed157600080fd5b505af1158015610ee5573d6000803e3d6000fd5b505050506040513d6020811015610efb57600080fd5b50519392505050565b600160a060020a03918216600090815260056020908152604080832093909416825291909152205490565b600654600160a060020a03163314610f4657600080fd5b6108ea8161127a565b610f598282610f64565b15156106c457600080fd5b600160a060020a03166000908152602091909152604090205460ff1690565b600082821115610f8f57fe5b50900390565b81810182811015610fa257fe5b92915050565b611012826007836040518082805190602001908083835b60208310610fde5780518252601f199092019160209182019101610fbf565b51815160209384036101000a60001901801990921691161790529201948552506040519384900301909220929150506112eb565b81600160a060020a03167fd211483f91fc6eff862467f8de606587a30c8fc9981056f051b897a418df803a826040518080602001828103825283818151815260200191508051906020019080838360005b8381101561107b578181015183820152602001611063565b50505050905090810190601f1680156110a85780820380516001836020036101000a031916815260200191505b509250505060405180910390a25050565b600160a060020a0382166000908152600360205260409020548111156110de57600080fd5b600160a060020a038216600090815260036020526040902054611107908263ffffffff610f8316565b600160a060020a038316600090815260036020526040902055600454611133908263ffffffff610f8316565b600455604080518281529051600160a060020a038416917fcc16f5dbb4873280815c1ee09dbd06736cffcc184412cf7a71a0fdb75d397ca5919081900360200190a2604080518281529051600091600160a060020a038516916000805160206113338339815191529181900360200190a35050565b611212826007836040518082805190602001908083835b602083106111de5780518252601f1990920191602091820191016111bf565b51815160209384036101000a600019018019909216911617905292019485525060405193849003019092209291505061130d565b81600160a060020a03167fbfec83d64eaa953f2708271a023ab9ee82057f8f3578d548c1a4ba0b5b700489826040518080602001828103825283818151815260200191508051906020019080838360008381101561107b578181015183820152602001611063565b600160a060020a038116151561128f57600080fd5b600654604051600160a060020a038084169216907f8be0079c531659141344cd1fd0a4f28419497f9722a3daafe3b4186f6b6457e090600090a360068054600160a060020a031916600160a060020a0392909216919091179055565b600160a060020a0316600090815260209190915260409020805460ff19169055565b600160a060020a0316600090815260209190915260409020805460ff191660011790555600ddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef8c5be1e5ebec7d5bd14f71427d1e84f3dd0314c0f7b2291e5b200ac8c7c3b925{bzzr}000000000000000000000000000000000000000000000000000000000000006000000000000000000000000000000000000000000000000000000000000000a00000000000000000000000000000000000000000000000000000000000000012000000000000000000000000000000000000000000000000000000000000000b47757468726965436f696e00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000034743540000000000000000000000000000000000000000000000000000000000`

They're SLIGHTLY different. Could you confirm my suspicion that the contract source is just out of date?

**Comment by vittominacori** [comment]
Hi, thank you for trying my project and, yes dist code was not updated with the latest improvements.
You can try with the updated code [ERC20Token.sol](https://github.com/vittominacori/erc20-generator/blob/master/dist/ERC20Token.sol
)

**Comment by jamesjguthrie** [comment]
That worked, thank you very much!
