### ISSUE TITLE
how can I edit the Contract adress

### ISSUE THREAD

**Issue by Speedevs** [vittominacori/erc20-generator#10]
How can I edit the contract address of the Token made with this

**Comment by vittominacori** [comment]
Why do you think that you can change address of a generated contract?

What do you mean?

**Comment by Speedevs** [comment]
Like edit token supply and increase it

**Comment by Speedevs** [comment]
After Token being created

**Comment by vittominacori** [comment]
You can’t increase supply. You can only mint until your cap is reached. 
Check the contract / write tab on etherscan.

**Comment by Speedevs** [comment]
Thanks
