### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by schrumpfmuffe** [vittominacori/erc20-generator#11]
Hi, 
it shows
Making transaction.
Please wait...

and then nothing more.
please advice.
thank you!

**Comment by vittominacori** [comment]
Hello, it should show your token address under this message when done.
Maybe you set a low gas price or the network needs more, so timing has been long than expected.

Please share trx hash here in order to check.

**Comment by schrumpfmuffe** [comment]
There is nothing i could set.i typed in name, symbol, etc. Via the creator and after the message, making transaction ,nothing else happens.

**Comment by vittominacori** [comment]
Yes it must be set in MetaMask (it sets them to best values but sometimes network can switch quickly).

Anyway check your last transaction on Etherscan or share your address/transaction here. I will check.

**Comment by schrumpfmuffe** [comment]
![15857368501425397208183128914643](https://user-images.githubusercontent.com/62889995/78127311-2eb4f300-7414-11ea-8554-c2c23de34ec8.jpg)

**Comment by schrumpfmuffe** [comment]
I see nothing more....

**Comment by vittominacori** [comment]
Did MetaMask popup open and you confirmed transaction on it or are you unable to confirm transaction?

**Comment by schrumpfmuffe** [comment]
no, MetaMask does not popup open, so that i cannot confirm the transaction.

**Comment by vittominacori** [comment]
Check by clicking on your metamask plugin on top of your browser. In case reject transaction and try again. If it not show you the popup click on the fox.

**Comment by schrumpfmuffe** [comment]
Hi i am sorry my metamask plugin on chrome shows, that it is connected with the website, but nothing happens when i click on the fox. there is also no pop up. i do not want to bother you. sorry.

**Comment by vittominacori** [comment]
I think you didn't confirm when popup shows. Try again. 
If it says to connect then say yes, and then confirm transaction.

**Comment by schrumpfmuffe** [comment]
There is no pop-up. so I cannot confirm the transaction

**Comment by vittominacori** [comment]
Go in Settings, Connections.

Look for `vittominacori.github.io` and remove. Then reload page and try again. 

![image](https://user-images.githubusercontent.com/8151143/78148871-a21b2c80-7435-11ea-9a66-012d0471cf60.png)

**Comment by schrumpfmuffe** [comment]
it says " do you want to connect with ....." i confirmed it. but no popup later.....

**Comment by vittominacori** [comment]
and no numbers near your fox? Like a notification?

**Comment by schrumpfmuffe** [comment]
no nothing

**Comment by vittominacori** [comment]
I can't help you guy. Inspect page to check for ja errors or send a screencast or screenshot of the entire process.

**Comment by schrumpfmuffe** [comment]
ok. thank you for your patience
