### ISSUE TITLE
Unable to increase fee

### ISSUE THREAD

**Issue by IntegersOfK** [vittominacori/erc20-generator#16]
Hi, I made a new contract with your cool website (thank you!) and it seemed like my fee was going to be too low to be confirmed in any reasonable timeframe. So I went back and tried to increase the fee with MetaMask before confirming the contract transaction, but the transaction doesn't appear to respect what I've chosen in the MetaMask GUI ("fast").

My [contract creation transaction](https://etherscan.io/tx/0x73570fb8ae566eec58742b8b3f842f4caac3b10a5d239abdf64e306e5474b258) was ultimately broadcasted with a lower fee than I selected and I'm still waiting for it to be confirmed. 

Is there something I'm doing wrong? Is the fee encoded directly into the hex data provided by the site or something? If so, maybe we need a way to increase that fee from the website. Or is there something up with MetaMask refusing to update fee for contract transaction? Thanks for any tips you can provide.

**Comment by vittominacori** [comment]
Hello, you should be able to Speed up your transaction in MetaMask modal.

![image](https://user-images.githubusercontent.com/8151143/80813771-f3504480-8bca-11ea-8d6c-73d022eb07e2.png)

**Comment by IntegersOfK** [comment]
Oh great thank you for the idea! But actually, I don't see that pending transaction in my MetaMask modal but I downloaded MyCrypto Wallet and was able to use the "Contracts" tab to paste in the same data to rebroadcast with a higher fee.

It's [now confirmed](https://etherscan.io/tx/0x6fbdaf0aa4eaa1b8ed3b5f58db37e17cb777cb924ff5e22c9439295e06cff475), thanks again for such a cool tool!

**Comment by lmnope1** [comment]
My metamask defaults to super low gas (like 8 cents). It is good to know that 4million has worked for @IntegersOfK . Thanks for sharing.
