### ISSUE TITLE
Waiting for transaction completion

### ISSUE THREAD

**Issue by GPcanada** [vittominacori/erc20-generator#17]
Hi Vittorio, I used your erc20 generator about 10hrs ago to create my tokens and Etherscan is still showing the transaction is pending with a duration time of more than 9.45hrs.  Does it usually take this long?

**Comment by vittominacori** [comment]
Hello, it usually takes less but network is slow these days due to high gas price. You should wait until it will be confirmed or you can speed up transaction with metamask by increasing gas price.

**Comment by GPcanada** [comment]
Ok, I'll try that.  Thank you
