### ISSUE TITLE
How many ethereum needed?

### ISSUE THREAD

**Issue by computermobil** [vittominacori/erc20-generator#2]
Hi Vitto!
Very nice Script, but one newbie question here: How many Ethereum do i need in main network to create a live ERC20 Token?
Thank you in advance!

**Comment by vittominacori** [comment]
Hi @computermobil 

[BASE](https://etherscan.io/token/0xb5c64c7d6b374ad738e314eaa7bcc07aec194b7b) Token was deployed using it.

It used 1,914,201 gas so setting a gas price of 3 gwei it cost 0.005742603 Ether.

Check the deployment transaction https://etherscan.io/tx/0xc599a725631fbed33b169fc392885672e19f19fc1e4f99c16bda8d3c5b3db674
