### ISSUE TITLE
why

### ISSUE THREAD

**Issue by Qzhanghuangyu** [vittominacori/erc20-generator#22]
Warning! Error encountered during contract execution [Out of gas]

**Comment by vittominacori** [comment]
You set a lower gas limit. 
Accept gas limit suggested by MetaMask. 
It should be about 4M. Check [here](https://etherscan.io/tx/0xc06a1e053942cac0c05c70952fd6450927a701c5c19911c8c0b30ecca1f3aaa8)

**Comment by kirkins** [comment]
Anyway to lower the cost? This seems really expensive.

**Comment by kirkins** [comment]
In my case it is suggesting a gas fee of 1.095373 ETH.

**Comment by vittominacori** [comment]
Gas price is really high in these moments.

You can just set a lower price but trx could be completed in days.

Check gas price here https://ethgasstation.info/

Now MetaMask is suggesting 82gwei for a max of 0.3 ETH.

We can't do more.

**Comment by kirkins** [comment]
@vittominacori ok thanks! I guess we are experiencing all time highs for eth gas prices right now. Starting to question if I can even use Ethereum, even a simple trade seems to cost a fortune.
