### ISSUE TITLE
Updated code

### ISSUE THREAD

**Issue by drtiger9** [vittominacori/erc20-generator#23]
Dear Dev

When was the code last updated (or is it automatically)? 
Is it still safe to use for issuing tokens (with minimum vulnerability)?

**Comment by vittominacori** [comment]
Code is updated to solidity 0.6.6.

Etherscan reports only very low severity 

```
Compiler specific version warnings:


The compiled contract might be susceptible to MissingEscapingInFormatting (very low-severity), 

ArraySliceDynamicallyEncodedBaseType (very low-severity),

ImplicitConstructorCallvalueCheck (very low-severity) Solidity Compiler Bugs.
```

On [next/dapp](https://github.com/vittominacori/erc20-generator/tree/next/dapp) branch you will find updated bytecode with 0.6.12 but it is not already live. Updated source code is on `master` branch.

I will put it live next weeks. I'm waiting for GAS price to be stable.

**Comment by vittominacori** [comment]
Now updated to solidity 0.7.1
