### ISSUE TITLE
Custom networks?

### ISSUE THREAD

**Issue by jaygaga** [vittominacori/erc20-generator#24]
Hello how can custom networks be added?

**Comment by vittominacori** [comment]
No way to do it on live website.

You should add your network in [dapp.js](https://github.com/vittominacori/erc20-generator/blob/dapp/.vuepress/mixins/dapp.js) as other networks are.

Then you should compile and run locally.

You can add your network on MetaMask and use it.

**Comment by jaygaga** [comment]
Ok cool thanks
