### ISSUE TITLE
How to recover eth sent to contract address

### ISSUE THREAD

**Issue by Speedevs** [vittominacori/erc20-generator#25]
is there any possible way to recovering te ethereum sent to hte contract address?? thank you

**Comment by vittominacori** [comment]
Do you mean the GAS fee?

**Comment by Speedevs** [comment]
No like I mean assuming someone send eth to this contract address
https://etherscan.io/token/0xa7c8d7a1c894e51dbb7c680b5b1dbdc845bfbdab

Can it be recovered

**Comment by Speedevs** [comment]
Want to know if it can or cannot and also if you have an ICO repository ,i.e if someone send ETH he automatically receive some tokens

**Comment by vittominacori** [comment]
No, token contract cannot receive ETH.

If you want to build an ICO check [this repo](https://github.com/vittominacori/ico-maker)
