### ISSUE TITLE
This contract may be abstract,and how to deploy this contract use Remix

### ISSUE THREAD

**Issue by kenneth** [vittominacori/erc20-generator#27]
This contract may be abstract, not implement an abstract parent's methods completely or not invoke an inherited contract's constructor correctly.

how to deploy this contract use Remix

**Comment by vittominacori** [comment]
It is not intended to be extended. 
If you want to deploy using remix use the [flattened](https://github.com/vittominacori/erc20-generator/blob/master/dist/BaseToken.dist.sol) version.

**Comment by kenneth** [comment]
ok,thank you for you reply.
