### ISSUE TITLE
Stuck while creating contract (still queued) since hours

### ISSUE THREAD

**Issue by marcincts** [vittominacori/erc20-generator#28]
Hello

I still get the same message while creating the contract.

I generated 3 contracts with a different fee and they are still not even pending.

What could be wrong?

I used https://vittominacori.github.io/erc20-generator/

Please help

![001](https://user-images.githubusercontent.com/47465687/95423806-fe5d8c80-0941-11eb-8424-c1c524c74b78.png)
![002](https://user-images.githubusercontent.com/47465687/95423811-00275000-0942-11eb-8fe3-da23fa7da16b.png)
![003](https://user-images.githubusercontent.com/47465687/95423817-01f11380-0942-11eb-9fc5-010968dbf5f5.png)

**Comment by marcincts** [comment]
Ok i try FIREFOX instead Chrome, Brave and success :) 
Thanks mate!

**Comment by vittominacori** [comment]
Is that your address? **0x5b3dc75337e85e14416677c398d46225b6f6247d**
It seems you have a [pending trx](https://etherscan.io/tx/0x9f6a08d2f9b96da6b6751026997c87b9c9bfd759d5b52d1c9728472092f1e514) with Nonce 1 having a gas fee of 3gwei. 
Until this will be pending you can't do any other transaction. 

Try cancelling your 3gwei transaction by following this [MetaMask tutorial](https://metamask.zendesk.com/hc/en-us/articles/360015489251-How-to-Speed-Up-or-Cancel-a-Pending-Transaction).
