### ISSUE TITLE
Issue with contract deploying 

### ISSUE THREAD

**Issue by Bobbyeternal** [vittominacori/erc20-generator#29]
Hi Vittorio, 
Please can you advise what is going wrong with an attempt to create ERC-20 token on your platform. Once I try to deploy a contract it shows me error (Error: [ethjs-rpc] rpc error with payload {"id":4426492818857,"jsonrpc":"2.0","params"...)
Thank you for your answer and advice)

<img width="400" alt="111" src="https://user-images.githubusercontent.com/72699451/96190495-02456c00-0f4b-11eb-84ef-1be3e61290cf.png">
<img width="322" alt="222" src="https://user-images.githubusercontent.com/72699451/96190504-06718980-0f4b-11eb-8718-e682721b3522.png">
<img width="356" alt="333" src="https://user-images.githubusercontent.com/72699451/96190508-08d3e380-0f4b-11eb-99d2-ecb972720ade.png">

**Comment by vittominacori** [comment]
You should leave the Gas Limit suggested by MetaMask.

If it sets 21000 you should manually set as about 4000000.

![image](https://user-images.githubusercontent.com/8151143/96261905-5428d900-0fc1-11eb-8133-016b8690ceff.png)

**Comment by Bobbyeternal** [comment]
Thank you for you prompt reply! If the fast price now 85 Gwei. Is there any reason to put price around 36-50 Gwei or it can pending for days? thanks)

**Comment by Bobbyeternal** [comment]
thank you! Much appreciate your help.
