### ISSUE TITLE
Fresh npm install reports vulnerabilities

### ISSUE THREAD

**Issue by hahla** [vittominacori/erc20-generator#3]
Hi @vittominacori 
Apologizes if this is not new information, but in the chance it is relevant I thought it might be helpful to community to share and address in core repo.  Please let me know your thoughts.

Best

######
git:(master) ✗ npm version
{ 'erc20-generator': '2.1.1',
  npm: '6.7.0',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.10.1',
  openssl: '1.0.2k',
  uv: '1.9.1',
  v8: '5.1.281.95',
  zlib: '1.2.8' } 

git:(master) ✗ npm audit
                                                                                
                       === npm audit security report ===                        
                                                                                
# Run  npm install --save-dev openzeppelin-test-helpers@0.3.2  to resolve 2 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ openzeppelin-test-helpers [dev]                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ openzeppelin-test-helpers > truffle-contract >               │
│               │ truffle-interface-adapter > web3 > web3-bzz > swarm-js >     │
│               │ tar.gz > tar                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ openzeppelin-test-helpers [dev]                              │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ openzeppelin-test-helpers > truffle-contract > web3 >        │
│               │ web3-bzz > swarm-js > tar.gz > tar                           │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

# Run  npm install --save-dev truffle-flattener@1.3.0  to resolve 2 vulnerabilities
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ truffle-flattener [dev]                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ truffle-flattener > truffle-config > truffle-provider >      │
│               │ truffle-interface-adapter > web3 > web3-bzz > swarm-js >     │
│               │ tar.gz > tar                                                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Arbitrary File Overwrite                                     │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ tar                                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ truffle-flattener [dev]                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ truffle-flattener > truffle-config > truffle-provider > web3 │
│               │ > web3-bzz > swarm-js > tar.gz > tar                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/803                             │
└───────────────┴──────────────────────────────────────────────────────────────┘

┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │
└──────────────────────────────────────────────────────────────────────────────┘
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ braces                                                       │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ lite-server [dev]                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ lite-server > browser-sync > micromatch > braces             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/786                             │
└───────────────┴──────────────────────────────────────────────────────────────┘
found 5 vulnerabilities (1 low, 4 high) in 445899 scanned packages
  run `npm audit fix` to fix 4 of them.
  1 vulnerability requires manual review. See the full report for details.

**Comment by vittominacori** [comment]
Hello @hahla,
thanks for reporting this.

I've just updated dependencies including `openzeppelin-test-helpers`.

I've pinned the `truffle-flattener` version to 1.2.11 because of they have an issue with duplicate interfaces ([#40](https://github.com/nomiclabs/truffle-flattener/issues/40)). So updating to 1.3.0 will produce a bad flatten code. I will update soon when they will resolve this issue.
