### ISSUE TITLE
change name builton

### ISSUE THREAD

**Issue by ockang** [vittominacori/erc20-generator#30]
![image](https://user-images.githubusercontent.com/4240285/96513928-6cfbed80-1252-11eb-99ec-fa4807655386.png)

**Comment by vittominacori** [comment]
You can't remove properties from an already deployed token.

It is a credit for generator to be used for free. I'm working on a new version where you will be able to deploy new token without credits for a little ETH fee. Keep updated

**Comment by ockang** [comment]
I understand, I made modifications to the core and it worked perfect
