### ISSUE TITLE
verification failed

### ISSUE THREAD

**Issue by bitdaric** [vittominacori/erc20-generator#32]
Compiler debug log:
 Error! Unable to generate Contract ByteCode and ABI
 Found the following ContractName(s) in source code : AccessControl, Address, BaseToken, Context, ERC1363, ERC165, ERC165Checker, ERC20, ERC20Base, ERC20Burnable, ERC20Capped, EnumerableSet, IERC1363, IERC1363Receiver, IERC1363Spender, IERC165, IERC20, Ownable, Roles, SafeMath, TokenRecover
 But we were unable to locate a matching bytecode (err_code_2)

I get this error from etherscan when I want to verify contract

**Comment by vittominacori** [comment]
If you used the generator your code should be already verified in both main or test network.

If you are compiling code by yourself you need to have the flattened code using truffle flattener.

Check [here](https://github.com/vittominacori/erc20-generator#flattener)

**Comment by vittominacori** [comment]
@bitdaric have you solved your issue?

**Comment by vittominacori** [comment]
closing. open again if still fails

**Comment by jayateertha043** [comment]
Hi just need some details ......

We get the bytecode and abi only after compiling right?
But I see that in deploy code you have the byte code constant from a JSON ABI file.

Can you please explain how it works?

Are you compiling the contract and getting the bytecode each time before deploy?

Thanks and Regards
Jayateertha G

**Comment by vittominacori** [comment]
Contracts are compiled and then I use the artifact. 

Bytecode and ABI are in a json file, the one generated by truffle.

You don't need to verify your source code because of it is already verified.
