### ISSUE TITLE
Add transaction fees

### ISSUE THREAD

**Issue by dinarpay** [vittominacori/erc20-generator#35]
Hello
I have an Ethereum Sidechain Network
ERC20 smart contracts are accepted
A flat fee is paid for the Sidechain Network
How can I add transaction fees to my smart contract users?
Knowing, I want to create a stablecoin and fixed transaction fees are deducted from my stablecoin currency
Openzeppelin is not required because we will not use the Ethereum network for transactions, so no gas fees

**Comment by vittominacori** [comment]
I'm sorry but I can't understand your issue related to current repository. 
Please reopen with more details.
