### ISSUE TITLE
ERC-721 Generator

### ISSUE THREAD

**Issue by jacksonverificer** [vittominacori/erc20-generator#37]
Hi, how can I implement a simple ERC-721 generator application like the way you did in erc20-generator?

**Comment by vittominacori** [comment]
It's not easy as ERC20 because of NFT may have different properties to be set so you cannot define a standard contract.

Try looking at https://vittominacori.github.io/cryptogift/ that it is a NFT Marketplace, NOT a NFT Generator.

Closing issue as it is not related.
