### ISSUE TITLE
delimit the token symbol field in UI

### ISSUE THREAD

**Issue by 1blockologist** [vittominacori/erc20-generator#44]
Your UI makes assumptions about the length of the token symbol and limits the user input to 5 characters which is a premature optimization. 

No wallet imposes this limitation, the erc20 standard doesn't impose this limitation, no block explorer, and AMMs the rest of the Defi infrastructure is built to accommodate that as well. Only a few exchanges had the limitation in times past. And now, many tokens have prefixes and suffixes and namespacing all in the symbol field.

Removing the limit in your reference implementation (via changing the code base here) would be ideal

As this is a field check only, and is not validated later on, just removing "max-length="5"" in the browser inspector is a workaround, and also the solution for your code

**Comment by vittominacori** [comment]
updated maxlen to 10 chars
