### ISSUE TITLE
Optional Proxy for upgrading contracts

### ISSUE THREAD

**Issue by 1blockologist** [vittominacori/erc20-generator#45]
The proxy contract is great when you plan additional features. Retains certain variables in the upgrade. Also a good way to have people coming back for more. (without them needing to airdrop tokens to all the holders or something)

For example, lets say you wanted to implement a transaction fee in the transfer methods. You could upgrade the token to do that.

https://docs.openzeppelin.com/upgrades-plugins/1.x/proxies

The desired functionality is an additional checkbox or option to add/deploy a proxy contract alongside of the token.

**Comment by vittominacori** [comment]
Yes it could be really useful but I can't guarantee that you are upgrading from a valid erc20, or that you are not changing your token behaviors (i.e. adding mintable behaviours in not mintable token without communicating to your holders).

Proxy behaviours is powerful in custom developed token but is really hard to cover in a "token generator".

I will evaluate to add this feature in the future.

**Comment by 1blockologist** [comment]
Accurate but an owner changing token behaviors is not your problem.

Proxy behavior can also be "dumb", where it just stores the balances map on upgrade, and the token behind it can upgrade to all sorts of functionality. A dumb proxy that you help people deploy would be valuable.

If it still becomes something out of the original scope, an owner or issuer really wants to change things they can still do airdrops or claimable airdrops for a completely different token meant to replace the original.
