### ISSUE TITLE
Is it possible to select the PowerfulERC20 package, but unlimited tokens?

### ISSUE THREAD

**Issue by meness** [vittominacori/erc20-generator#47]
Hi,

PowerfulERC20 package has a capped type, but I need an unlimited one. Is it possible?

**Comment by vittominacori** [comment]
Actually not. You could set a very high amount of tokens for total supply in order to have the ability to mint until this amount.

As it is a requested feature from many users I'm considering to add a new token type in the next few days.

**Comment by meness** [comment]
@vittominacori Does this technically work?

**Comment by vittominacori** [comment]
Yes it works.
You can use higher cap or you can wait few days to have the unlimited one built on the platform.

What features of PowerfulERC20 are you interested in?

**Comment by meness** [comment]
PowerfulERC20 has good enough features for requirements, but I need to have an unlimited tokens option.

**Comment by vittominacori** [comment]
Hello I added UnlimitedERC20 and AmazingERC20 which have not a cap on totale supply.

Take a look.
