### ISSUE TITLE
Need Deploy Information

### ISSUE THREAD

**Issue by jayateertha043** [vittominacori/erc20-generator#49]
Hi just need some details ......

We get the bytecode and abi only after compiling right?
But I see that in deploy code you have the byte code constant from a JSON ABI file.

Can you please explain how it works?

Are you compiling the contract and getting the bytecode each time before deploy?

Thanks and Regards
Jayateertha G

**Comment by vittominacori** [comment]
Closing due duplicate issue. Check #32
