### ISSUE TITLE
How to get the ABI ?

### ISSUE THREAD

**Issue by Azila92** [vittominacori/erc20-generator#55]
Hello,

Thank you for your ERC20 Generator.
I generated an ERC20 Token on Ropsten but I am unable to get the ABI. When I click on View on Etherscan, I am unable to get the ABI information on the contract tab. 

Could you please help.
Thank you

**Comment by vittominacori** [comment]
Contracts are not verified on all test networks. 
It will be visible on mainnet where contracts will be automatically verified.

Anyway you can get ABI on doc page https://vittominacori.github.io/erc20-generator/docs/
