### ISSUE TITLE
How to verify contract automatically?

### ISSUE THREAD

**Issue by blocksera** [vittominacori/erc20-generator#7]
Hi,

We're figuring out how you auto verify contract in your Dapp. There is no associated code for that. Could you help us?

**Comment by vittominacori** [comment]
Hi @blocksera 
If you mean how to verify on Etherscan, it is because of I verified it for this [token](https://etherscan.io/address/0x149e42662e99330889664eee7b474d9eedc40a12#code).

Then when you deploy your token it matches exactly my code and it is verified by default for this reason.

**Comment by blocksera** [comment]
That explains everything, thank you @vittominacori
