### ISSUE TITLE
Host on Hosting

### ISSUE THREAD

**Issue by imskaaz** [vittominacori/erc20-generator#8]
How to run in on Cpanel ?

**Comment by vittominacori** [comment]
Build the dapp branch then copy the .vuepress/dist folder in your root.

**Comment by imskaaz** [comment]
trying on ercgen.localbitcoin.id

**Comment by vittominacori** [comment]
No guy you should build using npm and copy files from dist folder.

**Comment by imskaaz** [comment]
Build complete and working on localhost, are i need to use vuepress too on cpanel ?

**Comment by vittominacori** [comment]
Yes you must use the build result. So the dist folder into vuepress.

**Comment by imskaaz** [comment]
Thanks for helping, one more question, how to change the fees and are thats fees ( GAS ) after create token connect to metamask will go to your wallet or not ? can you help me with this ?

**Comment by vittominacori** [comment]
There are no fees for me :)
GAS is to pay the Ethereum network in order to confirm your transaction.

**Comment by imskaaz** [comment]
sorry for asking more, can i make the fees more small ? or can i get profit when using your source ? like puting ads or other ? thanks

**Comment by vittominacori** [comment]
You guy can do whatever you want with my code. It is under MIT License.
We cannot make the fee smaller. It depends on GAS amount and GAS price you set making transaction. And obviously on current ETH exchange rate.
